version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
env:
  variables:
    REACT_APP_API_URL: "http://tmis-env.eba-75dbz5yv.ap-southeast-2.elasticbeanstalk.com"
